export const UPDATE_COURSES = 'COURSES/UPDATE_COURSES';
export const ADD_COURSE = 'COURSES/ADD_COURSE';
export const DELETE_COURSE = 'COURSES/DELETE_COURSE';
export const UPDATE_COURSE = 'COURSES/UPDATE_COURSE';
