export const ALL_COURSES = 'COURSES/ALL_COURSES';
export const UPDATE_COURSES = 'COURSES/UPDATE_COURSES';
export const CREATE_COURSE = 'COURSES/CREATE_COURSE';
export const DELETE_COURSE = 'COURSES/DELETE_COURSE';
